Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@Rayuduyarlagadda 
backspace-academy
/
aws-nodejs-sample-codebuild
Public
Code
Issues
Pull requests
6
Actions
Projects
Wiki
Security
Insights
aws-nodejs-sample-codebuild/buildspec.yml
@backspace-academy
backspace-academy Update buildspec.yml
Latest commit 5bc264a on Jul 16, 2019
 History
 1 contributor
34 lines (33 sloc)  1.02 KB
   
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing Mocha...

   build:
    commands:
      - echo "Zipping deployment package..."
      - zip -g deployment_package.zip Index.js
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name Serverless-api --zip-file fileb://deployment_package.zip
      - echo "DONE!!"

 